# Site settings
title: One Pink Pony
email: no-real-email@onepinkpony.eu
description: >
  One Pink Ponies mix of
  documentation and blog post pages.

baseurl: "" # the subpath of your site, e.g. /blog/
url: https://blog.onepinkpony.eu # the base hostname & protocol for your site
git_address: https://github.com/t-h-e
git_edit_address: https://github.com/t-h-e/jekyll-doc-theme/blob/oopblog

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: darkly

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
